Add Color to Output

diff --git a/timeshift-autosnap-apt b/timeshift-autosnap-apt
--- a/timeshift-autosnap-apt
+++ b/timeshift-autosnap-apt
@@ -2,9 +2,17 @@
 #original author: gobonja
 #adapted for apt by Willi Mutschler (wmutschl)
 
-[ $(findmnt / -no fstype) == "overlay" ] && { echo "==> skipping timeshift-autosnap because system is booted in Live CD mode..."; exit 0; }
+# General Formatting
+FORMATRESET="\x1B[0m"
+FORMATBRIGHT="\x1B[1m"
 
-[[ -v SKIP_AUTOSNAP ]] && { echo "==> skipping timeshift-autosnap due SKIP_AUTOSNAP environment variable being set."; exit 0; }
+# Foreground Colors
+TEXTRED="\x1B[31m"    #Warning
+TEXTYELLOW="\x1B[33m" #Recommended Commands / Extras
+
+[ $(findmnt / -no fstype) == "overlay" ] && { printf "${FORMATBRIGHT}${TEXTYELLOW}%s${FORMATRESET}\n" "==> skipping timeshift-autosnap because system is booted in Live CD mode..."; exit 0; }
+
+[[ -v SKIP_AUTOSNAP ]] && { printf "${FORMATBRIGHT}${TEXTYELLOW}%s${FORMATRESET}\n" "==> skipping timeshift-autosnap due SKIP_AUTOSNAP environment variable being set."; exit 0; }
 
 readonly CONF_FILE=/etc/timeshift-autosnap-apt.conf
 readonly SNAPSHOTS_TO_DELETE=$(mktemp -u --tmpdir ${0##*/}.XXXXXXXX)
@@ -13,7 +21,7 @@ readonly SNAPSHOT_NAME_DATE_PATTERN="[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_[0-9]\{2\}
 
 get_property() {
     if [ ! -f $CONF_FILE ]; then
-        echo "$CONF_FILE not found! Using $1=$3" >&2;
+        printf "${FORMATBRIGHT}${TEXTYELLOW}%s${FORMATRESET}\n" "$CONF_FILE not found! Using $1=$3" >&2;
         param_value=$3
     else
         param_value=`sed '/^\#/d' $CONF_FILE | grep $1 | tail -n 1 |\
@@ -22,7 +30,7 @@ get_property() {
         if ([ "$2" == "boolean" ] && [ "$param_value" != true ] && [ "$param_value" != false ]) || \
            ([ "$2" == "integer" ] && [[ ! "$param_value" =~ ^[-+]?([1-9][[:digit:]]*|1)$ ]]) || \
            ([ "$2" == "string" ] && [ "$param_value" == "" ]) ; then
-            echo "Wrong paramater in $CONF_FILE. Using $1=$3" >&2
+            printf "${FORMATBRIGHT}${TEXTYELLOW}%s${FORMATRESET}\n" "Wrong paramater in $CONF_FILE. Using $1=$3" >&2
             param_value=$3
         fi
     fi
@@ -31,18 +39,18 @@ get_property() {
 }
 
 if $(get_property "skipAutosnap" "boolean" "false") ; then
-    echo "==> skipping timeshift-autosnap-apt due skipAutosnap in $CONF_FILE set to TRUE." >&2; exit 0;
+    printf "${FORMATBRIGHT}${TEXTYELLOW}%s${FORMATRESET}\n" "==> skipping timeshift-autosnap-apt due skipAutosnap in $CONF_FILE set to TRUE." >&2; exit 0;
 fi
 
 if $(get_property "snapshotBoot" "boolean" "true") ; then
-    echo "Rsyncing /boot into the filesystem before the call to timeshift." >&2;
+    printf "${FORMATBRIGHT}${TEXTYELLOW}%s${FORMATRESET}\n" "Rsyncing /boot into the filesystem before the call to timeshift." >&2;
     mkdir -p /boot.backup
     cmd="rsync -au --exclude 'efi' --delete /boot/ /boot.backup/"
     eval $cmd
 fi
 
 if $(get_property "snapshotEFI" "boolean" "true") ; then
-    echo "Rsyncing /boot/efi into the filesystem before the call to timeshift." >&2;
+    printf "${FORMATBRIGHT}${TEXTYELLOW}%s${FORMATRESET}\n" "Rsyncing /boot/efi into the filesystem before the call to timeshift." >&2;
     mkdir -p /boot.backup
     mkdir -p /boot.backup/efi
     cmd="rsync -au --delete /boot/efi/ /boot.backup/efi/"
@@ -51,7 +59,8 @@ fi
 
 readonly SNAPSHOT_DESCRIPTION=$(get_property "snapshotDescription" "string" "{timeshift-autosnap-apt} {created before upgrade}")
 
-timeshift --create --comments "$SNAPSHOT_DESCRIPTION" || { echo "Unable to run timeshift-autosnap-apt! Please close Timeshift and try again. Script will now exit..." >&2; exit 1; }
+printf "${FORMATBRIGHT}${TEXTYELLOW}%s${FORMATRESET}\n" "Creating snapshot..." >&2
+timeshift --create --comments "$SNAPSHOT_DESCRIPTION" || { printf "${FORMATBRIGHT}${TEXTRED}%s${FORMATRESET}\n" "Unable to run timeshift-autosnap-apt! Please close Timeshift and try again. Script will now exit..." >&2; exit 1; }
 
 if $(get_property "deleteSnapshots" "boolean" "true") ; then
     timeshift --list > $SNAPSHOTS_TO_DELETE
